#!/usr/bin/env bash
# build-codex.sh
#
# Converts agents/*.md (markdown with YAML frontmatter) into Codex TOML
# subagent files installed at ~/.codex/agents/compass-<name>.toml.
#
# Usage:
#   bash scripts/build-codex.sh
#   bash scripts/build-codex.sh --dry-run   # print output, do not write files
#
# Requirements: bash, awk, sed — no external dependencies.
#
# Source format (agents/<name>.md):
#   ---
#   name: case-analyst
#   description: Extracts structured data from medical records and case files.
#   tools:
#     - filesystem
#     - web_search
#   ---
#   <markdown body — becomes the TOML prompt field>
#
# Output format (~/.codex/agents/compass-<name>.toml):
#   [agent]
#   name = "compass-case-analyst"
#   description = "Extracts structured data from medical records and case files."
#   tools = ["filesystem", "web_search"]
#   prompt = """
#   <markdown body>
#   """

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_DIR="$PLUGIN_ROOT/agents"
OUTPUT_DIR="${HOME}/.codex/agents"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
  echo "[dry-run] No files will be written."
fi

if [[ ! -d "$AGENTS_DIR" ]]; then
  echo "Error: agents/ directory not found at $AGENTS_DIR" >&2
  exit 1
fi

if [[ "$DRY_RUN" == "false" ]]; then
  mkdir -p "$OUTPUT_DIR"
fi

GENERATED=()

for agent_file in "$AGENTS_DIR"/*.md; do
  [[ -f "$agent_file" ]] || continue
  base="$(basename "$agent_file" .md)"

  # ── Parse YAML frontmatter ──────────────────────────────────────────────────
  # Extract everything between the first pair of --- delimiters.
  frontmatter="$(awk '/^---$/{if(++n==1){next} if(n==2){exit}} n==1{print}' "$agent_file")"

  if [[ -z "$frontmatter" ]]; then
    echo "Warning: no frontmatter in $agent_file — skipping." >&2
    continue
  fi

  # Parse individual fields from frontmatter.
  fm_name="$(echo "$frontmatter" | awk -F': ' '/^name:/{print $2}' | tr -d '[:space:]')"
  fm_description="$(echo "$frontmatter" | awk -F': ' '/^description:/{print $2}' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')"

  # Parse tools list — handles both inline and block list formats.
  fm_tools="$(echo "$frontmatter" | awk '
    /^tools:/{in_tools=1; next}
    in_tools && /^[[:space:]]*-[[:space:]]/{
      gsub(/^[[:space:]]*-[[:space:]]/, ""); gsub(/[[:space:]]*$/, ""); print; next
    }
    in_tools && /^[^[:space:]]/{in_tools=0}
  ')"

  # Use filename as fallback name.
  [[ -z "$fm_name" ]] && fm_name="$base"

  agent_name="compass-${fm_name}"
  output_file="$OUTPUT_DIR/${agent_name}.toml"

  # ── Extract markdown body (everything after the closing ---) ─────────────────
  body="$(awk '/^---$/{if(++n==2){found=1; next}} found{print}' "$agent_file")"

  # Escape backslashes and triple-quote sequences in body for TOML multi-line string.
  # TOML """ strings do not support escape sequences — we need to replace any
  # literal """ in the body with " " " (split across chars) to avoid terminating
  # the string early.
  body_escaped="$(echo "$body" | sed 's/"""/\" \" \"/g')"

  # ── Build tools TOML array ───────────────────────────────────────────────────
  tools_array="[]"
  if [[ -n "$fm_tools" ]]; then
    tools_joined="$(echo "$fm_tools" | awk 'NR>1{printf ", "} {printf "\"%s\"", $0} END{print ""}' | tr -d '\n')"
    tools_array="[$tools_joined]"
  fi

  # ── Render TOML ──────────────────────────────────────────────────────────────
  toml_content="[agent]
name = \"${agent_name}\"
description = \"${fm_description}\"
tools = ${tools_array}
prompt = \"\"\"
${body_escaped}
\"\"\""

  if [[ "$DRY_RUN" == "true" ]]; then
    echo ""
    echo "=== $output_file ==="
    echo "$toml_content"
  else
    echo "$toml_content" > "$output_file"
    echo "Written: $output_file"
  fi

  GENERATED+=("$agent_name")
done

if [[ ${#GENERATED[@]} -eq 0 ]]; then
  echo "No agent files found in $AGENTS_DIR."
  exit 0
fi

# ── Emit README ──────────────────────────────────────────────────────────────
readme_content="# Compass Codex Subagents

Generated by scripts/build-codex.sh from agents/*.md source files.
Installed at: ${OUTPUT_DIR}/

## Subagents installed

$(for name in "${GENERATED[@]}"; do echo "- ${name}  (~/.codex/agents/${name}.toml)"; done)

## Usage in Codex

Reference a subagent in your Codex session by its name:

    @${GENERATED[0]}  — (example)

Or let the Compass skills dispatch to subagents automatically via @mention.

## Re-generating

Run this script again after editing any agents/*.md source file:

    bash scripts/build-codex.sh

Use --dry-run to preview output without writing files:

    bash scripts/build-codex.sh --dry-run
"

if [[ "$DRY_RUN" == "true" ]]; then
  echo ""
  echo "=== ${OUTPUT_DIR}/README-compass.md ==="
  echo "$readme_content"
else
  echo "$readme_content" > "${OUTPUT_DIR}/README-compass.md"
  echo "Written: ${OUTPUT_DIR}/README-compass.md"
  echo ""
  echo "Done. ${#GENERATED[@]} subagent(s) installed at ${OUTPUT_DIR}/."
fi
